name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run: |
        pip3 install --user django
        sudo apt-get build-dep python-psycopg2
        pip3 install psycopg2-binary
        python3 manage.py test
